"""
Django settings for phone_patchwork project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8jram1l^7q414x!4$tm^j_yuro!@18-z9h(17z5c%8c+=$v&od'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

	'searchphone',
    'eth_patchwork',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'phone_patchwork.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'phone_patchwork.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

API_42_CONFIG = {
    'client_ID' : 'ba080f64b6bea0941942813b34719aa57a7c182e29943e5f8c485d16f670cca7',
    'client_secret' : '4d2acb8e7596de9c843dee2ce4f9638ce34200c2daaa92270c4b8e70dec194bf',
}

USERS_42_DEBUG = [
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'URQUIZAR',
        'firstname':'Clémentine',
        'login':'curquiza',
        'phone':'+33 6 61 01 68 77',
    },
    {
        'name':'GUILLIER',
        'firstname':'Paul',
        'login':'pguillie',
        'phone':'+33 6 86 32 79 19',
    },
    {
        'name':'FICARA',
        'firstname':'Gabriele',
        'login':'gficara',
        'phone':'+33 7 67 04 74 64',
    },
    {
        'name':'DUDNICZENKO',
        'firstname':'Nicolas',
        'login':'ndudnicz',
        'phone':'+33 7 66 59 79 15',
    },
    {
        'name':'NACACHE',
        'firstname':'Yohan',
        'login':'ynacache',
        'phone':'+33 7 62 83 14 86',
    },
    {
        'name':'LEVEQUE',
        'firstname':'Alexis',
        'login':'aleveque',
        'phone':'+33 7 70 52 71 08',
    },
    {
        'name':'DEL CARMEN',
        'firstname':'Fabien',
        'login':'fdel-car',
        'phone':'+33 7 66 52 30 86',
    },
    {
        'name':'DESVERNAY',
        'firstname':'Charles Henry',
        'login':'cdesvern',
        'phone':'+33 6 65 54 58 80',
    },
    {
        'name':'MOUSSA',
        'firstname':'Hamza',
        'login':'hmoussa',
        'phone':'+33 6 21 16 89 88',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
    {
        'name':'BONNEFON',
        'firstname':'Sylvain',
        'login':'sbonnefo',
        'phone':'+33 6 10 58 78 83',
    },
        
    

]